### ISSUE TITLE
Gettings maps for the paticipant at #maps - ERROR:  userID = 1

### ISSUE THREAD

**Issue by sinisarudan** [mprinc/KnAllEdge#200]
REST request looks then like : 
http://knalledge.org:8888/kmaps/by-participant/1.json

**On client we get**
```
zone.js:101 GET http://localhost:8888/kmaps/by-participant/1.json 500 (Internal Server Error)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM818:3(anonymous function) @ angular.js:11881sendReq @ angular.js:11642serverRequest @ angular.js:11352processQueue @ angular.js:16170(anonymous function) @ angular.js:16186$eval @ angular.js:17444$digest @ angular.js:17257$apply @ angular.js:17552done @ angular.js:11697completeRequest @ angular.js:11903requestLoaded @ angular.js:11836wrapFn @ zone.js:769ZoneDelegate.invokeTask @ zone.js:356onInvokeTask @ ng_zone_impl.ts:61ZoneDelegate.invokeTask @ zone.js:355Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
angular.js:13708 SyntaxError: Unexpected token C in JSON at position 0
    at Object.parse (native)
    at transformResponse (http://localhost:5555/components/knalledgeMap/js/services.js:1858:27)
    at transformData (http://localhost:5555/node_modules/angular/angular.js:10602:12)
```

**Because server breaks and returns wrong result**
```
CastError: Cast to ObjectId failed for value "1" at path "participants"
   at ObjectId.cast (/var/www/knalledge/src/backend/node_modules/mongoose/lib/schema/objectid.js:123:13)
   at ObjectId.castForQuery (/var/www/knalledge/src/backend/node_modules/mongoose/lib/schema/objectid.js:172:17)
   at SchemaArray.castForQuery (/var/www/knalledge/src/backend/node_modules/mongoose/lib/schema/array.js:204:20)
   at module.exports (/var/www/knalledge/src/backend/node_modules/mongoose/lib/cast.js:202:32)
   at module.exports (/var/www/knalledge/src/backend/node_modules/mongoose/lib/cast.js:36:18)
   at Query.cast (/var/www/knalledge/src/backend/node_modules/mongoose/lib/query.js:2262:10)
   at Query.find (/var/www/knalledge/src/backend/node_modules/mongoose/lib/query.js:986:10)
   at Function.find (/var/www/knalledge/src/backend/node_modules/mongoose/lib/model.js:1019:13)
   at exports.index (/var/www/knalledge/src/backend/prod/modules/kMap.js:105:14)
   at /var/www/knalledge/src/backend/node_modules/express-resource/index.js:172:7
   at callbacks (/var/www/knalledge/src/backend/node_modules/express/lib/router/index.js:164:37)
   at param (/var/www/knalledge/src/backend/node_modules/express/lib/router/index.js:138:11)
   at param (/var/www/knalledge/src/backend/node_modules/express/lib/router/index.js:135:11)
   at param (/var/www/knalledge/src/backend/node_modules/express/lib/router/index.js:135:11)
   at param (/var/www/knalledge/src/backend/node_modules/express/lib/router/index.js:135:11)
   at param (/var/www/knalledge/src/backend/node_modules/express/lib/router/index.js:135:11)
```

**Comment by sinisarudan** [comment]
@mprinc 's comment:

error happens although I'm logged in:
```
Logged in user info
Name:Sasha
Surname:Rudan
Display name:Sasha
Affiliation:
email:mprinc@gmail.com
user id:556760847125996dc1a4a241
map Maps

```

IT looks like this, when I log in again:

```
Logged in user info
Name:Sasha
Surname:Rudan
Display name:Sasha
Affiliation:
email:mprinc@gmail.com
user id:55268521fb9a901e442172f8
map Maps
```

**Comment by sinisarudan** [comment]
⚠️  💣  IMPORTANT!! regarding LIVE-debugging, with console.log("...", object);
here we see, that this kind of logging, displayed the value that is NOW and not at the moment it was logged!
![error](https://cloud.githubusercontent.com/assets/1769627/17064489/06c8dd4c-503d-11e6-8545-9b0a5f4af4f9.jpg)
so, we have like a regular _id, but above we see that it was 1, user was not loaded, he was local

**Comment by sinisarudan** [comment]
It was **racing-problem**!
User whoAmi was not loaded at the moment of requiring its id for getting his maps,
so we used local._id = 1, and **due to above-mentioned debugging issue**, we saw it as a correct _id!!

Fixed, now, with changes to use promises and to set $resolved = true after loading whoAmI from server.

Supported non-logged-in users, without errors and showing them only public maps and preventing them from creating/importing maps

**Comment by sinisarudan** [comment]
It was **racing-problem**!
User whoAmi was not loaded at the moment of requiring its id for getting his maps,
so we used local._id = 1, and **due to above-mentioned debugging issue**, we saw it as a correct _id!!

Fixed, now, with changes to use promises and to set $resolved = true after loading whoAmI from server.

Supported non-logged-in users, without errors and showing them only public maps and preventing them from creating/importing maps
